name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Download solution
        uses: actions/checkout@v3
      - name: Print cmake version
        run: cmake --version
      - name: Print compiler version
        run: ${{matrix.compiler.command}} ${{matrix.compiler.version-flags}}
      - run: pwd
      - run: ls
      - run: mkdir build && cd build
      - run: ls
      - run: mkdir release && cd release
      - run: pwd
      - run: pwd ../..
      - run: cmake ../..
      - name: Compile with cmake
        run: cmake -DCMAKE_BUILD_TYPE=Debug --build .
      - run: cd ../..
      - name: Run tests
        run: bash tests/run_tests.sh build/release


