name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run-compile:
    runs-on: windows
    steps:
      - name: Download solution
        uses: actions/checkout@v3
      - name: Print cmake version
        run: cmake --version
      - name: Print compiler version
        run: ${{matrix.compiler.command}} ${{matrix.compiler.version-flags}}
      - name: Setup build directories
        run: |
          mkdir build
          cd build 
          mkdir release
          mkdir debug
      - name: Create Makefiles
        run: |
          cd build/release
          cmake ../..
          cd ../debug
          cmake ../..
      - name: Compile debug with cmake
        run: |
          cd build/debug
          cmake -DCMAKE_BUILD_TYPE=Debug --build .
      - name: Compile release with cmake
        run: |
          cd build/release
          cmake -DCMAKE_BUILD_TYPE=Release --build .
      - name: Run tests
        run: bash tests/run_tests.sh ../build/release


